name: Deploy Banking Admin Preview

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build:preview
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo mkdir -p /var/www/banking-admin-preview
          sudo chown -R $USER:$USER /var/www/banking-admin-preview
          
    - name: Upload files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "dist/banking-admin/*"
        target: "/var/www/banking-admin-preview/"
        strip_components: 2
        
    - name: Set permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/banking-admin-preview
          sudo chmod -R 755 /var/www/banking-admin-preview