name: Deploy Banking Admin Preview

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for preview
      run: npm run build:preview
      
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          # Create directory if it doesn't exist
          sudo mkdir -p /var/www/banking-admin-preview
          sudo chown -R $USER:$USER /var/www/banking-admin-preview
          
    - name: Upload build files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "dist/banking-admin/*"
        target: "/var/www/banking-admin-preview/"
        strip_components: 2
        
    - name: Set file permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo chown -R www-data:www-data /var/www/banking-admin-preview
          sudo chmod -R 755 /var/www/banking-admin-preview
          
          # Test if files were deployed correctly
          if [ -f "/var/www/banking-admin-preview/index.html" ]; then
            echo "Deployment successful - index.html found"
          else
            echo "Deployment failed - index.html not found"
            exit 1
          fi