name: Deploy Banking Admin Preview

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /var/www/banking-admin-preview
          git pull origin main
          npm ci
          npm run build:preview
          sudo cp -r dist/banking-admin/* ./
          sudo chown -R www-data:www-data /var/www/banking-admin-preview
          sudo chmod -R 755 /var/www/banking-admin-preview